import type { CredentialCategory, CredentialStatus } from '@prisma/client';
import type { DemoPack } from '../types';
import { d, daysFromToday } from '../date-helpers';

const workspace = {
  name: 'Northline Petroleum Co.',
  contactName: 'Diana Namutebi',
  contactEmail: 'hr@northline.imara.co.ke',
  contactPhone: '+256 414 000000',
  postalAddress: 'Retail & depot operations — Uganda and Kenya',
  county: 'East Africa (KE / UG)',
  employeeNumberPrefix: 'NLP',
  payrollFrequency: 'monthly',
  leavePayMode: 'none',
} as const;

const departments = [
  'Retail Operations',
  'Depot & Logistics',
  'LPG Division',
  'Fleet & Cards',
  'Finance',
  'HSE',
  'Human Resources',
  'IT & Systems',
] as const;

const employees = [
  {
    employeeNumber: 'NLP-UG-001',
    firstName: 'Moses',
    lastName: 'Okello',
    role: 'Station Attendant — Nansana Station, Uganda',
    department: 'Retail Operations',
    email: 'moses.okello@northline.imara.co.ke',
    phone: '+256 700 100001',
    idNumber: 'NLP-EMP-001',
    kraPin: 'A012NLP001K',
    nssfNumber: 'NLP-NSSF-001',
    nhifNumber: 'NLP-NHIF-001',
    dateOfJoining: d(2022, 3, 15),
    baseSalary: 48000,
    allowances: [{ name: 'Shift', amount: 8000 }, { name: 'Transport', amount: 5000 }],
    bankName: 'Stanbic Bank Uganda',
    bankBranch: 'Kampala',
    bankAccountNumber: '9030001001',
  },
  {
    employeeNumber: 'NLP-UG-002',
    firstName: 'Grace',
    lastName: 'Nakato',
    role: 'Station Supervisor — Nansana Station, Uganda',
    department: 'Retail Operations',
    email: 'grace.nakato@northline.imara.co.ke',
    phone: '+256 700 100002',
    idNumber: 'NLP-EMP-002',
    kraPin: 'A012NLP002K',
    nssfNumber: 'NLP-NSSF-002',
    nhifNumber: 'NLP-NHIF-002',
    dateOfJoining: d(2021, 7, 1),
    baseSalary: 78000,
    allowances: [{ name: 'Shift', amount: 12000 }, { name: 'Transport', amount: 6000 }],
    bankName: 'Centenary Bank',
    bankBranch: 'Nansana',
    bankAccountNumber: '9030001002',
  },
  {
    employeeNumber: 'NLP-UG-003',
    firstName: 'Robert',
    lastName: 'Ssemwogerere',
    role: 'Station Attendant — Kampala Central, Uganda',
    department: 'Retail Operations',
    email: 'robert.ssem@northline.imara.co.ke',
    phone: '+256 700 100003',
    idNumber: 'NLP-EMP-003',
    kraPin: 'A012NLP003K',
    nssfNumber: 'NLP-NSSF-003',
    nhifNumber: 'NLP-NHIF-003',
    dateOfJoining: d(2023, 1, 10),
    baseSalary: 47000,
    allowances: [{ name: 'Shift', amount: 8000 }, { name: 'Transport', amount: 5000 }],
    bankName: 'Equity Bank Uganda',
    bankBranch: 'CBD',
    bankAccountNumber: '9030001003',
  },
  {
    employeeNumber: 'NLP-UG-004',
    firstName: 'Harriet',
    lastName: 'Amanya',
    role: 'LPG Field Agent Coordinator — Entebbe Road, Uganda',
    department: 'LPG Division',
    email: 'harriet.amanya@northline.imara.co.ke',
    phone: '+256 700 100004',
    idNumber: 'NLP-EMP-004',
    kraPin: 'A012NLP004K',
    nssfNumber: 'NLP-NSSF-004',
    nhifNumber: 'NLP-NHIF-004',
    dateOfJoining: d(2022, 11, 1),
    baseSalary: 98000,
    allowances: [{ name: 'Field', amount: 18000 }, { name: 'Transport', amount: 10000 }],
    bankName: 'Absa Bank Uganda',
    bankBranch: 'Entebbe Road',
    bankAccountNumber: '9030001004',
  },
  {
    employeeNumber: 'NLP-UG-005',
    firstName: 'Paul',
    lastName: 'Mugisha',
    role: 'Depot Supervisor — Jinja Road, Uganda',
    department: 'Depot & Logistics',
    email: 'paul.mugisha@northline.imara.co.ke',
    phone: '+256 700 100005',
    idNumber: 'NLP-EMP-005',
    kraPin: 'A012NLP005K',
    nssfNumber: 'NLP-NSSF-005',
    nhifNumber: 'NLP-NHIF-005',
    dateOfJoining: d(2020, 5, 20),
    baseSalary: 115000,
    allowances: [{ name: 'Responsibility', amount: 22000 }, { name: 'Transport', amount: 12000 }],
    bankName: 'DFCU Bank',
    bankBranch: 'Jinja Road',
    bankAccountNumber: '9030001005',
  },
  {
    employeeNumber: 'NLP-KE-001',
    firstName: 'Brian',
    lastName: 'Otieno',
    role: 'Station Attendant — Nairobi West, Kenya',
    department: 'Retail Operations',
    email: 'brian.otieno@northline.imara.co.ke',
    phone: '+254 711 200001',
    idNumber: 'NLP-EMP-006',
    kraPin: 'A012NLP006K',
    nssfNumber: '20000000001',
    nhifNumber: '30000000001',
    dateOfJoining: d(2023, 4, 1),
    baseSalary: 52000,
    allowances: [{ name: 'Shift', amount: 9000 }, { name: 'Transport', amount: 6000 }],
    bankName: 'KCB Bank',
    bankBranch: 'Nairobi West',
    bankAccountNumber: '1100020001',
  },
  {
    employeeNumber: 'NLP-KE-002',
    firstName: 'Aisha',
    lastName: 'Wanjiru',
    role: 'Station Supervisor — Mombasa Road, Kenya',
    department: 'Retail Operations',
    email: 'aisha.wanjiru@northline.imara.co.ke',
    phone: '+254 711 200002',
    idNumber: 'NLP-EMP-007',
    kraPin: 'A012NLP007K',
    nssfNumber: '20000000002',
    nhifNumber: '30000000002',
    dateOfJoining: d(2022, 8, 15),
    baseSalary: 82000,
    allowances: [{ name: 'Shift', amount: 14000 }, { name: 'Transport', amount: 8000 }],
    bankName: 'Equity Bank',
    bankBranch: 'Mombasa Road',
    bankAccountNumber: '1100020002',
  },
  {
    employeeNumber: 'NLP-KE-003',
    firstName: 'Kevin',
    lastName: 'Kamau',
    role: 'Fleet Card Relationship Manager — Westlands, Kenya',
    department: 'Fleet & Cards',
    email: 'kevin.kamau@northline.imara.co.ke',
    phone: '+254 711 200003',
    idNumber: 'NLP-EMP-008',
    kraPin: 'A012NLP008K',
    nssfNumber: '20000000003',
    nhifNumber: '30000000003',
    dateOfJoining: d(2023, 2, 1),
    baseSalary: 135000,
    allowances: [{ name: 'Performance', amount: 25000 }, { name: 'Transport', amount: 12000 }],
    bankName: 'NCBA Bank',
    bankBranch: 'Westlands',
    bankAccountNumber: '1100020003',
  },
  {
    employeeNumber: 'NLP-UG-006',
    firstName: 'Diana',
    lastName: 'Namutebi',
    role: 'HR Manager — Kampala Central, Uganda',
    department: 'Human Resources',
    email: 'diana.namutebi@northline.imara.co.ke',
    phone: '+256 700 100006',
    idNumber: 'NLP-EMP-009',
    kraPin: 'A012NLP009K',
    nssfNumber: 'NLP-NSSF-009',
    nhifNumber: 'NLP-NHIF-009',
    dateOfJoining: d(2021, 1, 15),
    baseSalary: 165000,
    allowances: [{ name: 'Housing', amount: 28000 }, { name: 'Transport', amount: 12000 }],
    bankName: 'Stanbic Bank Uganda',
    bankBranch: 'Kololo',
    bankAccountNumber: '9030001006',
  },
  {
    employeeNumber: 'NLP-KE-004',
    firstName: 'James',
    lastName: 'Mwangi',
    role: 'Finance Officer — Nairobi West, Kenya',
    department: 'Finance',
    email: 'james.mwangi@northline.imara.co.ke',
    phone: '+254 711 200004',
    idNumber: 'NLP-EMP-010',
    kraPin: 'A012NLP010K',
    nssfNumber: '20000000004',
    nhifNumber: '30000000004',
    dateOfJoining: d(2022, 3, 1),
    baseSalary: 128000,
    allowances: [{ name: 'Housing', amount: 22000 }, { name: 'Transport', amount: 10000 }],
    bankName: 'Co-operative Bank',
    bankBranch: 'Upper Hill',
    bankAccountNumber: '1100020004',
  },
];


const careersJobs = [
  {
    title: 'Regional Retail Manager — East Africa',
    location: 'Nairobi, Kenya (Uganda travel)',
    type: 'Full Time',
    category: 'Retail Leadership',
    description:
      'Own retail performance, compliance, and customer experience across Northline forecourt and convenience sites in Kenya and Uganda. You will partner with station supervisors, depot logistics, and HQ on KPIs, audits, and growth initiatives.',
    requirements: [
      '8+ years in fuel retail, convenience, or multi-site operations',
      'Proven P&L and people leadership across distributed teams',
      'Experience with ERC (Kenya) / PPDA (Uganda) retail compliance is a strong plus',
      'Willingness to travel between Nairobi and Kampala monthly',
    ],
    responsibilities: [
      'Drive sales, margin, and HSSE targets for the regional retail portfolio',
      'Lead quarterly operational audits and corrective action plans',
      'Coach station supervisors and align rota coverage with peak demand',
      'Represent Northline with landlords, regulators, and key fleet accounts',
    ],
    benefits: ['Competitive package', 'Company vehicle allowance', 'Medical cover', 'Performance bonus'],
    skills: ['Retail Operations', 'Forecourt Safety', 'P&L Management', 'Stakeholder Management'],
    salary: { min: 280000, max: 420000, currency: 'KES' },
    salaryPublic: true,
    experience: '8+ years multi-site fuel or retail operations',
    education: "Bachelor's in Business, Engineering, or related field",
    minYearsExperience: 8,
    educationLevel: 'Bachelor',
    educationQualification: 'Business, Commerce, Engineering, or Operations Management',
    requiredCertifications: 'OSH / first-response training for fuel sites preferred',
    deadlineDaysFromNow: 58,
  },
  {
    title: 'Station Supervisor — Kampala',
    location: 'Kampala, Uganda',
    type: 'Full Time',
    category: 'Retail Operations',
    description:
      'Lead a high-volume Northline station team: shift planning, cash and stock controls, customer service, and day-one compliance with fuel handling and fire-safety standards.',
    requirements: [
      '3+ years as a forecourt or station supervisor',
      'Strong cash, stock, and variance discipline',
      'Valid fuel-handling / site safety credentials (or ability to certify within 90 days)',
    ],
    responsibilities: [
      'Supervise attendants, cashiers, and LPG cylinder exchanges',
      'Complete opening/closing checklists and incident reporting',
      'Coordinate minor maintenance and escalate HSSE risks immediately',
    ],
    benefits: ['Shift allowance', 'Medical cover', 'Career path to area manager'],
    skills: ['Team Leadership', 'Cash Control', 'Customer Service', 'HSSE Awareness'],
    salary: { min: 1800000, max: 2600000, currency: 'UGX' },
    salaryPublic: true,
    experience: '3+ years in fuel retail or large-format retail supervision',
    education: 'Diploma or degree in a business or technical discipline',
    minYearsExperience: 3,
    educationLevel: 'Diploma',
    educationQualification: 'Business, Retail Management, or related',
    requiredCertifications: 'MEMD / site safety awareness for LPG and fuels',
    deadlineDaysFromNow: 52,
  },
  {
    title: 'Depot Operations Lead — Jinja Road',
    location: 'Kampala, Uganda',
    type: 'Full Time',
    category: 'Logistics & Supply',
    description:
      'Manage inbound/outbound bulk movements, loading schedules, and documentation for the Jinja Road depot. Ensure dangerous-goods protocols, stock accuracy, and 24/7 readiness for retail replenishment.',
    requirements: [
      '5+ years in fuels, terminals, or hazardous-goods logistics',
      'Experience with weighbridge, loading gantries, and fleet scheduling',
      'Comfortable with night and weekend escalation on-call rotations',
    ],
    responsibilities: [
      'Plan daily loading windows with transport and retail demand',
      'Maintain stock reconciliation and variance investigations',
      'Lead toolbox talks and permit-to-work for maintenance windows',
    ],
    benefits: ['On-call allowance', 'Medical cover', 'Pension where applicable'],
    skills: ['Bulk Fuels Handling', 'Scheduling', 'Dangerous Goods', 'Documentation'],
    salary: { min: 2200000, max: 3200000, currency: 'UGX' },
    salaryPublic: false,
    experience: '5+ years depot or terminal operations',
    education: 'Degree in Engineering, Logistics, or related',
    minYearsExperience: 5,
    educationLevel: 'Bachelor',
    educationQualification: 'Mechanical, Chemical, Logistics, or Supply Chain',
    requiredCertifications: 'Dangerous goods / transport certification preferred',
    deadlineDaysFromNow: 60,
  },
  {
    title: 'LPG Distribution Coordinator',
    location: 'Kampala, Uganda',
    type: 'Full Time',
    category: 'LPG',
    description:
      'Coordinate cylinder exchange routes, third-party hauliers, and depot stock for LPG. Be the operational link between retail sites, field agents, and compliance on cylinder tracking and customer safety.',
    requirements: [
      '3+ years in LPG, bottled gas, or last-mile distribution',
      'Strong Excel / ERP literacy for route and inventory planning',
      'Field-first mindset with valid driving licence',
    ],
    responsibilities: [
      'Optimise daily routes and cylinder balances across stations',
      'Track incidents, near-misses, and regulator reporting timelines',
      'Support sales campaigns for domestic and commercial LPG accounts',
    ],
    benefits: ['Field allowance', 'Medical cover', 'Sales incentives'],
    skills: ['Route Planning', 'Inventory Control', 'LPG Safety', 'Vendor Coordination'],
    salary: { min: 1900000, max: 2700000, currency: 'UGX' },
    salaryPublic: true,
    experience: '3+ years LPG or packaged distribution',
    education: 'Diploma or degree in Logistics, Business, or Engineering',
    minYearsExperience: 3,
    educationLevel: 'Diploma',
    educationQualification: 'Logistics, Operations, or Engineering technology',
    requiredCertifications: null,
    deadlineDaysFromNow: 48,
  },
  {
    title: 'Fleet Card Relationship Executive',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Sales & Fleet',
    description:
      'Grow Northline fleet card adoption with SMEs, logistics firms, and public-sector fleets. Own onboarding, spend analytics, and renewals while coordinating with retail sites for acceptance and dispute resolution.',
    requirements: [
      '4+ years B2B sales in payments, fuel cards, or logistics services',
      'Track record closing multi-stakeholder deals',
      'CRM discipline and comfortable presenting data to finance buyers',
    ],
    responsibilities: [
      'Prospect, pitch, and onboard fleet accounts',
      'Run quarterly business reviews with key fleet customers',
      'Feed product insights from the field to HQ marketing',
    ],
    benefits: ['Competitive OTE', 'Medical cover', 'Company laptop & airtime'],
    skills: ['B2B Sales', 'CRM', 'Negotiation', 'Data Presentation'],
    salary: { min: 140000, max: 220000, currency: 'KES' },
    salaryPublic: true,
    experience: '4+ years B2B sales or account management',
    education: "Bachelor's in Marketing, Commerce, or related",
    minYearsExperience: 4,
    educationLevel: 'Bachelor',
    educationQualification: 'Commerce, Marketing, Business Administration',
    requiredCertifications: null,
    deadlineDaysFromNow: 55,
  },
  {
    title: 'HSE Officer — Retail & Depots',
    location: 'Nairobi, Kenya (regional travel)',
    type: 'Full Time',
    category: 'Health, Safety & Environment',
    description:
      'Embed HSSE culture across Northline retail and depot assets in Kenya: inspections, incident investigations, contractor controls, and regulatory liaison with ERC and county teams.',
    requirements: [
      'NEBOSH IGC or equivalent; 4+ years HSE in fuels, chemicals, or logistics',
      'Experience delivering toolbox talks and audit programmes',
      'Strong written communication for regulator correspondence',
    ],
    responsibilities: [
      'Schedule and document site inspections with corrective actions',
      'Lead incident investigations and lessons-learned sessions',
      'Maintain contractor HSE files and PTW oversight',
    ],
    benefits: ['Medical cover', 'Professional membership support', 'Travel per diem'],
    skills: ['Incident Investigation', 'Risk Assessment', 'Training Delivery', 'Regulatory Engagement'],
    salary: { min: 160000, max: 240000, currency: 'KES' },
    salaryPublic: false,
    experience: '4+ years HSE in industrial or retail fuel environments',
    education: 'Degree in Environmental Science, Engineering, or Occupational Health',
    minYearsExperience: 4,
    educationLevel: 'Bachelor',
    educationQualification: 'Environmental, Mechanical, or Safety Engineering',
    requiredCertifications: 'NEBOSH IGC or equivalent',
    deadlineDaysFromNow: 50,
  },
  {
    title: 'HR Business Partner — Field Operations',
    location: 'Kampala, Uganda',
    type: 'Full Time',
    category: 'Human Resources',
    description:
      'Partner with retail and depot leaders on workforce planning, performance cycles, and employee relations for a growing multi-country footprint.',
    requirements: [
      '5+ years HR BP or HR generalist experience in retail or logistics',
      'Solid knowledge of Uganda employment law and practice',
      'Experience with HRIS and payroll interfaces',
    ],
    responsibilities: [
      'Support hiring, onboarding, and probation for frontline roles',
      'Coach managers on performance, discipline, and grievance handling',
      'Drive engagement and communication programmes for shift staff',
    ],
    benefits: ['Medical cover', 'Hybrid working where role allows', 'Learning budget'],
    skills: ['Employee Relations', 'Workforce Planning', 'HRIS', 'Coaching'],
    salary: { min: 2400000, max: 3600000, currency: 'UGX' },
    salaryPublic: false,
    experience: '5+ years HR business partnering',
    education: "Bachelor's in HR, Psychology, or related",
    minYearsExperience: 5,
    educationLevel: 'Bachelor',
    educationQualification: 'Human Resource Management, Psychology, Industrial Relations',
    requiredCertifications: 'IHRM or equivalent membership preferred',
    deadlineDaysFromNow: 56,
  },
  {
    title: 'Finance Analyst — Retail & Cards',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Finance',
    description:
      'Support management reporting for retail margins, fleet card revenue, and working capital. Partner with operations on variance analysis and statutory timelines.',
    requirements: [
      'CPA II minimum (or ACCA equivalent) with 3+ years relevant experience',
      'Advanced Excel; experience with ERP retail modules is a plus',
      'Comfortable translating operational KPIs into finance narratives',
    ],
    responsibilities: [
      'Produce weekly margin and volume dashboards by region',
      'Support month-end close for retail and cards business lines',
      'Assist external audit and tax queries with clean documentation',
    ],
    benefits: ['Medical cover', 'Study support for CPA final', 'Bonus scheme'],
    skills: ['Financial Modelling', 'ERP', 'Variance Analysis', 'Reporting'],
    salary: { min: 130000, max: 190000, currency: 'KES' },
    salaryPublic: false,
    experience: '3+ years finance analysis in retail, FMCG, or payments',
    education: "Bachelor's in Finance, Accounting, or Commerce",
    minYearsExperience: 3,
    educationLevel: 'Bachelor',
    educationQualification: 'Commerce, Accounting, Finance, or Economics',
    requiredCertifications: 'CPA II or ACCA equivalent',
    deadlineDaysFromNow: 47,
  },
  {
    title: 'IT Systems Analyst — POS & Forecourt',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Technology',
    description:
      'Own stability and enhancements for point-of-sale, tank gauging, and integrations used at Northline sites. Be the bridge between vendors, cybersecurity, and retail operations.',
    requirements: [
      '4+ years supporting retail or hospitality POS ecosystems',
      'Understanding of payment flows, VPNs, and remote site connectivity',
      'Ability to document SOPs and train station supervisors',
    ],
    responsibilities: [
      'Triage incidents, escalate vendors, and track root-cause fixes',
      'Test releases for POS and forecourt peripherals',
      'Maintain asset inventory and patch compliance for sites',
    ],
    benefits: ['Medical cover', 'Certification budget', 'Hybrid working'],
    skills: ['POS Support', 'Networking', 'SQL', 'Documentation'],
    salary: { min: 150000, max: 210000, currency: 'KES' },
    salaryPublic: true,
    experience: '4+ years IT support or business systems analysis',
    education: 'Degree in IT, Computer Science, or related',
    minYearsExperience: 4,
    educationLevel: 'Bachelor',
    educationQualification: 'Computer Science, Information Systems, or Software Engineering',
    requiredCertifications: null,
    deadlineDaysFromNow: 59,
  },
  {
    title: 'Graduate Trainee Programme — Retail Operations',
    location: 'Kampala & Nairobi (rotations)',
    type: 'Full Time',
    category: 'Early Careers',
    description:
      'Two-year accelerated programme across station operations, depot shadowing, and HQ projects. Designed for graduates who want to grow into supervisory roles in fuel retail.',
    requirements: [
      "Bachelor's completed within the last 24 months (any discipline)",
      'High energy, customer-centric mindset, and mobility between cities',
      'Leadership experience through campus, volunteer, or work placements',
    ],
    responsibilities: [
      'Complete structured rotations with competency sign-offs',
      'Deliver a capstone project on customer experience or HSSE',
      'Participate in community and brand activations',
    ],
    benefits: ['Mentorship', 'Medical cover', 'Programme stipend plus performance uplift'],
    skills: ['Communication', 'Problem Solving', 'Teamwork', 'Data Literacy'],
    salary: { min: 850000, max: 1200000, currency: 'UGX' },
    salaryPublic: true,
    experience: '0–1 years professional experience (graduate)',
    education: "Bachelor's degree (any discipline)",
    minYearsExperience: 0,
    educationLevel: 'Bachelor',
    educationQualification: 'Open — strong academic record and extracurricular leadership',
    requiredCertifications: null,
    deadlineDaysFromNow: 45,
  },
];


const credentials = [
    {
      email: 'moses.okello@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'PPDA-UG-MO-001',
      authority: 'PPDA Uganda',
      issue: d(2023, 4, 1),
      expiry: d(2026, 8, 1),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'moses.okello@northline.imara.co.ke',
      category: 'training' as CredentialCategory,
      name: 'Fire Safety Certificate',
      number: 'UFB-MO-002',
      authority: 'Uganda Fire Brigade',
      issue: d(2024, 1, 10),
      expiry: daysFromToday(10),
      status: 'expiring_soon' as CredentialStatus,
    },
    {
      email: 'grace.nakato@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'PPDA-UG-GN-001',
      authority: 'PPDA Uganda',
      issue: d(2022, 8, 1),
      expiry: d(2026, 2, 10),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'grace.nakato@northline.imara.co.ke',
      category: 'life_support' as CredentialCategory,
      name: 'First Aid Certificate',
      number: 'URC-GN-002',
      authority: 'Uganda Red Cross',
      issue: d(2024, 5, 1),
      expiry: daysFromToday(12),
      status: 'expiring_soon' as CredentialStatus,
    },
    {
      email: 'robert.ssem@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'PPDA-UG-RS-001',
      authority: 'PPDA Uganda',
      issue: d(2022, 6, 1),
      expiry: daysFromToday(-28),
      status: 'expired' as CredentialStatus,
    },
    {
      email: 'harriet.amanya@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'LPG Handling Certification',
      number: 'MEMD-HA-001',
      authority: 'MEMD Uganda',
      issue: d(2023, 2, 1),
      expiry: d(2026, 1, 15),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'harriet.amanya@northline.imara.co.ke',
      category: 'training' as CredentialCategory,
      name: 'Fire Safety Certificate',
      number: 'UFB-HA-002',
      authority: 'Uganda Fire Brigade',
      issue: d(2024, 3, 15),
      expiry: d(2026, 7, 1),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'paul.mugisha@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'PPDA-UG-PM-001',
      authority: 'PPDA Uganda',
      issue: d(2021, 1, 10),
      expiry: d(2026, 5, 20),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'paul.mugisha@northline.imara.co.ke',
      category: 'oil_gas_operations' as CredentialCategory,
      name: 'Dangerous Goods Transport Certificate',
      number: 'UNRA-PM-002',
      authority: 'UNRA',
      issue: d(2023, 9, 1),
      expiry: daysFromToday(16),
      status: 'expiring_soon' as CredentialStatus,
    },
    {
      email: 'brian.otieno@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'ERC-KE-BO-001',
      authority: 'ERC Kenya',
      issue: d(2023, 5, 1),
      expiry: d(2026, 10, 15),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'aisha.wanjiru@northline.imara.co.ke',
      category: 'regulatory_compliance' as CredentialCategory,
      name: 'Fuel Handling Licence',
      number: 'ERC-KE-AW-001',
      authority: 'ERC Kenya',
      issue: d(2022, 10, 1),
      expiry: d(2026, 3, 1),
      status: 'active' as CredentialStatus,
    },
    {
      email: 'aisha.wanjiru@northline.imara.co.ke',
      category: 'training' as CredentialCategory,
      name: 'Fire Safety Certificate',
      number: 'KFB-AW-002',
      authority: 'Kenya Fire Brigade',
      issue: d(2024, 2, 1),
      expiry: daysFromToday(9),
      status: 'expiring_soon' as CredentialStatus,
    },
  ];

export const petroleumRetailPack: DemoPack = {
  id: 'petroleum-retail',
  label: 'Petroleum Retail (Northline-style)',
  workspace,
  recruitmentEmployer: 'Northline Petroleum Co.',
  entities: {
    ke: {
      code: 'ke',
      legalName: 'Northline Kenya Ltd',
      contactName: workspace.contactName,
      contactEmail: 'hr.ke@northline.imara.co.ke',
      contactPhone: '+254 709 000000',
      postalAddress: 'Nairobi — retail, depot, fleet',
      county: 'Kenya',
      employeeNumberPrefix: 'NLP-KE',
      currency: 'KES',
    },
    ug: {
      code: 'ug',
      legalName: 'Northline Uganda Ltd',
      contactName: workspace.contactName,
      contactEmail: 'hr.ug@northline.imara.co.ke',
      contactPhone: '+256 414 000000',
      postalAddress: 'Kampala — retail, depot, LPG',
      county: 'Uganda',
      employeeNumberPrefix: 'NLP-UG',
      currency: 'UGX',
    },
  },
  legacyWorkspaceNames: ['Northline Petroleum Co.', 'Northline Kenya Ltd', 'Demo Corporation'],
  departments,
  employees,
  careersJobs,
  credentials,
  pipelineEmailDomain: 'pipeline.demo.northline.imara.co.ke',
  jobReferenceCode: 'NLP',
  slugToken: 'nlp',
  demoPassword: 'Demo@2026!',
  staffUsers: {
    admin: { email: 'demo@northline.imara.co.ke', name: 'Amina Njeri' },
    hr: { email: 'diana.namutebi@northline.imara.co.ke', name: 'Diana Namutebi' },
    finance: { email: 'james.mwangi@northline.imara.co.ke', name: 'James Mwangi' },
    ess: { email: 'moses.okello@northline.imara.co.ke', name: 'Moses Okello' },
    roleEmails: {
      brian: 'brian.otieno@northline.imara.co.ke',
      grace: 'grace.nakato@northline.imara.co.ke',
      aisha: 'aisha.wanjiru@northline.imara.co.ke',
      robert: 'robert.ssem@northline.imara.co.ke',
      james: 'james.mwangi@northline.imara.co.ke',
      paul: 'paul.mugisha@northline.imara.co.ke',
      moses: 'moses.okello@northline.imara.co.ke',
      harriet: 'harriet.amanya@northline.imara.co.ke',
      kevin: 'kevin.kamau@northline.imara.co.ke',
      diana: 'diana.namutebi@northline.imara.co.ke',
    },
  },
  interviewLocations: {
    video: 'https://meet.northline.imara.co.ke/demo-interview-room',
    onsite: 'Northline — Kampala HQ, Boardroom East (demo address)',
  },
  interviewBreakJobTitleIncludes: 'Station Supervisor',
  companySetup: {
    appName: 'Stride',
    orgName: 'Northline Petroleum Co.',
    tagline: 'Petroleum retail operations — forecourts, depots, and fleet across East Africa.',
    wordmark: 'Northline Petroleum Co.',
    contactEmail: 'hello@northline.imara.co.ke',
    contactPhone: '+256 414 000000',
    contactAddress: 'Retail & depot operations — Uganda and Kenya',
    careersEmployerName: 'Northline Petroleum Co.',
    careersTagline: 'Petroleum retail operations — forecourts, depots, and fleet across East Africa.',
    staffLoginWelcomeTitle: 'Welcome to Northline Petroleum Co.',
    staffLoginWelcomeSubtitle: 'Sign in to manage retail and depot workforce',
    essLoginWelcomeTitle: 'Employee Self Service',
    essLoginWelcomeSubtitle: 'View payslips, leave, and personal details',
    payslipLegalName: 'Northline Petroleum Co.',
    emailFromName: 'Northline Petroleum Co. HR',
    publicFooterText:
      'Northline Petroleum Co. — petroleum retail across Kenya and Uganda. Forecourt, depot, LPG, and fleet operations.',
  },
};
