#!/usr/bin/env node
/**
 * RAV-62: Generate Postgres RLS policies from schema.prisma tenant models.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(__dirname, '../prisma/schema.prisma');
const outPath = resolve(__dirname, '../prisma/migrations/rls_policies.sql');

const GLOBAL_MODELS = new Set([
  'User',
  'PermissionDefinition',
  'RolePermission',
  'SchedulerLock',
]);

const schema = readFileSync(schemaPath, 'utf8');
const models = [...schema.matchAll(/^model (\w+) \{/gm)].map((m) => m[1]);

const lines = [
  '-- RAV-62: Row-Level Security policies (generated by scripts/generate-rls-sql.mjs)',
  '-- Apply after organizationId columns exist: npm run db:rls',
  '',
];

function tenantPolicy(table) {
  return [
    `ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE "${table}" FORCE ROW LEVEL SECURITY;`,
    '',
    `DROP POLICY IF EXISTS "${table}_tenant_rw" ON "${table}";`,
    `CREATE POLICY "${table}_tenant_rw" ON "${table}"`,
    '  FOR ALL',
    `  USING ("organizationId" = current_setting('app.current_org', true)::uuid)`,
    `  WITH CHECK ("organizationId" = current_setting('app.current_org', true)::uuid);`,
    '',
    `DROP POLICY IF EXISTS "${table}_insert_bootstrap" ON "${table}";`,
    `CREATE POLICY "${table}_insert_bootstrap" ON "${table}"`,
    '  FOR INSERT',
    '  WITH CHECK (',
    "    coalesce(current_setting('app.current_org', true), '') = ''",
    "    OR \"organizationId\" = current_setting('app.current_org', true)::uuid",
    '  );',
    '',
  ];
}

// Organization table — special policies (match platform/0001_rls.sql).
lines.push(
  'ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "Organization" FORCE ROW LEVEL SECURITY;',
  '',
  'DROP POLICY IF EXISTS "Organization_insert_bootstrap" ON "Organization";',
  'CREATE POLICY "Organization_insert_bootstrap" ON "Organization"',
  '  FOR INSERT',
  "  WITH CHECK (coalesce(current_setting('app.current_org', true), '') = '');",
  '',
  'DROP POLICY IF EXISTS "Organization_tenant_select" ON "Organization";',
  'CREATE POLICY "Organization_tenant_select" ON "Organization"',
  '  FOR SELECT',
  '  USING (id = current_setting(\'app.current_org\', true)::uuid);',
  '',
  'DROP POLICY IF EXISTS "Organization_tenant_update" ON "Organization";',
  'CREATE POLICY "Organization_tenant_update" ON "Organization"',
  '  FOR UPDATE',
  '  USING (id = current_setting(\'app.current_org\', true)::uuid)',
  '  WITH CHECK (id = current_setting(\'app.current_org\', true)::uuid);',
  '',
);

for (const model of models) {
  if (GLOBAL_MODELS.has(model) || model === 'Organization') continue;
  lines.push(...tenantPolicy(model));
}

lines.push(
  '-- Global tables (no RLS): User, PermissionDefinition, RolePermission, SchedulerLock',
);

writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote RLS policies for ${models.length - GLOBAL_MODELS.size - 1} tables → ${outPath}`);
